title: "InfinityFit"
description: "Empowering wearable technology for a healthier tomorrow."
url: "https://lyeong1010.github.io/InfinityFit"
repository: "https://github.com/lyeong1010/InfinityFit"

collections:
  workouts:
    output: true
