theme: jekyll-theme-minimal
title: InfinityFit
description: Empowering wearable technology for a healthier tomorrow.
url: "https://lyeong1010.github.io/InfinityFit"
repository: "https://github.com/lyeong1010/InfinityFit"

# 커스텀 CSS 파일 추가 (스타일 수정)
style: /assets/css/custom.css

# 사이트 기본 설정 (URL, 이메일 등)
email: dmsdn01@naver.com

collections:
  workouts:
    output: true
