theme: jekyll-theme-cayman
title: InfinityFit
description: Empowering wearable technology for a healthier tomorrow.
url: "https://lyeong1010.github.io/InfinityFit"
repository: "https://github.com/lyeong1010/InfinityFit"
email: your-email@example.com

collections:
  workouts:
    output: true # 컬렉션을 HTML로 출력
