name: 📚 Documentation Improvement
description: Suggest improvements to InfinityFit's documentation
title: "[DOCS] Brief description of documentation improvement"
labels: documentation
body:
  - type: markdown
    attributes:
      value: |
        **Documentation Section**  
        Specify the part of the documentation that needs improvement.

  - type: textarea
    attributes:
      label: Improvement Details
      description: Describe the suggested improvement in detail

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other relevant details, examples, or links
