name: 🚀 Feature Request
description: Suggest a new feature or enhancement for InfinityFit
title: "[FEATURE] Brief description of the feature"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        **Feature Description**  
        Describe the new feature or improvement you’re suggesting.

  - type: textarea
    attributes:
      label: Problem Statement
      description: Explain why this feature is needed or what problem it solves

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe how you think this feature could be implemented

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions you’ve thought about

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or details related to the feature
