name: ❓ Question / Support Request
description: Ask a question or request support regarding InfinityFit
title: "[QUESTION] Brief description of your question"
labels: question
body:
  - type: markdown
    attributes:
      value: |
        **Question**  
        Describe your question or the support you need.

  - type: textarea
    attributes:
      label: Context
      description: Provide any relevant context or background information

  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other details, screenshots, or links related to your question
